# параметры функций
function:
  func1: 
    name: 'exp' # y = exp(ax+b)
    a1: [0.5,5] 
    b1: [-0.69314718,  4.25]

  func2: 
    name: 'linexp' # y = a(x-b)*exp(-c(x-b))
    a2: [ 10, 1000 ]
    b2: [ -0.3, -0.05 ]
    c2: [ 4, 15 ]
    
# дни недели
# сезонность и тренд
trend: [-0.5, 2] # выбирается случайным образом из диапазона. Тренд = 1, означает что продажи за 1 год увеличатся в 2 раза
seasonality:
  A1: [0, 1] # диапазон амплитуд при синусоиде, 1-я гармоника. A=1 означает, что для максимальной точки (пике сезона продаж), 
   #  количество продаж увеличится в 2 раза (относительно среднего) в точке минимума синусоиды - продажи в 2 раза упадут
  A2: [0,0.7] # вторая гармоника
  fi: [-3.14,3.14] # фаза
# общие параметры цены, количества начальных точек и пр
price:
  num_points: 365 # количество сгенерированных точек (история для бандита)
  num_levels: 40 # количество ценовых уровней 
  