name: clip-siamese
channels:
  - conda-forge
  - pytorch
dependencies:
  # Python
  - python=3.13
  - pip

  # Core ML/DL packages
  - pytorch
  - torchvision  
  - transformers
  - timm
  - sentence-transformers
  - scikit-learn
  - datasets

  # Data processing
  - pandas
  - numpy
  - scipy

  # Computer vision
  - opencv
  - pillow

  # Utilities
  - tqdm
  - python-dotenv
  - pyyaml
  - requests
  - aiohttp

  # Jupyter environment  
  - jupyter
  - jupyterlab
  - ipywidgets
  - matplotlib

  # Experiment tracking
  - wandb
  - mlflow

  # HuggingFace
  - huggingface_hub

  # Additional packages via pip
  - pip:
    - more-itertools
    - torchinfo
    - data-parser

    # - selenium
    # - webdriver_manager
    # - selenium_stealth
    # - selenium-wire
    # - pyvirtualdisplay