name: clip-siamese
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.8
  - aiosignal=1.3.2
  - alembic=1.16.1
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - anyio=4.9.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.1
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.1
  - aws-c-io=0.19.1
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.0
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.8
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.13.3
  - cryptography=45.0.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - databricks-sdk=0.55.0
  - datasets=3.6.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dill=0.3.8
  - dnspython=2.7.0
  - docker-py=7.1.0
  - docker-pycreds=0.4.0
  - double-conversion=3.3.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - eval_type_backport=0.2.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - fastapi=0.115.12
  - fastapi-cli=0.0.7
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - flask=3.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.1
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.6.0
  - fsspec=2025.3.0
  - gdk-pixbuf=2.42.12
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.40.2
  - graphene=3.4.3
  - graphite2=1.3.13
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.2.2
  - gunicorn=23.0.0
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hdf5=1.14.6
  - hf-xet=1.1.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.32.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jasper=4.2.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.22.4
  - libabseil=20250127.1
  - libaec=1.1.3
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.6
  - libclang13=20.1.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.71.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm20=20.1.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopencv=4.11.0
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.6
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.7.0
  - libudev1=257.6
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.29
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.6
  - lz4-c=1.10.0
  - mako=1.3.10
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.3
  - mkl=2024.2.2
  - mlflow=2.22.0
  - mlflow-skinny=2.22.0
  - mlflow-ui=2.22.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.4.4
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-common=9.2.0
  - mysql-libs=9.2.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nlohmann_json=3.12.0
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - opencv=4.11.0
  - openexr=3.3.3
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.0
  - opentelemetry-api=1.34.0
  - opentelemetry-sdk=1.34.0
  - opentelemetry-semantic-conventions=0.55b0
  - optree=0.16.0
  - orc=2.1.2
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.3.0
  - pandocfilters=1.5.0
  - pango=1.56.3
  - paramiko=3.5.1
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.1
  - prometheus_flask_exporter=0.23.2
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-opencv=4.11.0
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pynacl=1.5.0
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pyside6=6.8.3
  - pysocks=1.7.1
  - python=3.13.3
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.1
  - python-gil=3.13.3
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.13
  - pytorch=2.7.0
  - pytz=2025.2
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt6-main=6.8.3
  - querystring_parser=1.2.4
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rich-toolkit=0.11.3
  - rpds-py=0.25.1
  - rsa=4.9.1
  - s2n=1.5.20
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.14
  - send2trash=1.8.3
  - sentence-transformers=4.1.0
  - sentry-sdk=2.29.1
  - setproctitle=1.3.6
  - setuptools=75.8.2
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlalchemy=2.0.41
  - sqlparse=0.5.3
  - stack_data=0.6.3
  - starlette=0.46.2
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - timm=1.0.15
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tomli=2.2.1
  - torchvision=0.22.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.52.4
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - types-python-dateutil=2.9.0.20250516
  - typing=3.10.0.0
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uri-template=1.3.0
  - urllib3=2.4.0
  - uvicorn=0.34.3
  - uvicorn-standard=0.34.3
  - uvloop=0.21.0
  - wandb=0.20.0
  - watchfiles=1.0.5
  - wayland=1.23.1
  - wayland-protocols=1.44
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - widgetsnbextension=4.0.14
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
    - more-itertools==10.7.0
    - data-parser==0.0.3
    - torchinfo==1.8.0

    # - PyVirtualDisplay==3.0
    # - selenium==4.33.0
    # - selenium-stealth==1.0.6
    # - selenium-wire==5.1.0
    # - webdriver-manager==4.0.2
