name: competitors-xgboost
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10 
  - ipykernel
  - flask
  - joblib
  - requests
  - xgboost
  - scikit-learn
  - transformers
  - sentence-transformers
  - pandas
  - numpy
  - more-itertools
  - pytorch  # If torch isn't available in conda, it can be installed via pip
  - torchvision
  - optuna
  - pytorch
  - pip:
    - python-math
    - cython
    - ruclip
