name: cross-encoder
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pytorch
  - pip
  - pip:
    - datasets
    - sentence-transformers
    - huggingface-hub
    - python-dotenv
    - tqdm
    - transformers
    - evaluate
    - numpy
    - pandas
    - scikit-learn
    - wandb
    - mlflow
    - ipykernel
    - jupyter
    - matplotlib
    - pillow
    - langchain
    - langchain-openai
    - langchain-core
    - rank-bm25 