name: cross-encoder
channels:
  - conda-forge
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cudatoolkit=11.8.0
  - filelock=3.18.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - openssl=3.5.0
  - pip=25.0.1
  - python=3.12.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=78.1.1
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.13.2
  - tzdata=2025b
  - wheel=0.45.1
  - yaml=0.2.5
  - pip:
    - datasets==3.5.0
    - evaluate==0.4.3
    - faiss-cpu==1.10.0
    - hdbscan==0.8.40
    - hf-xet==1.0.3
    - ipykernel==6.29.5
    - jupyter==1.1.1
    - langchain==0.3.23
    - langchain-community==0.3.21
    - langchain-openai==0.3.14
    - matplotlib==3.10.1
    - mlflow==2.22.0
    - numpy==2.2.5
    - openpyxl==3.1.5
    - pandas==2.2.3
    - python-dotenv==1.1.0
    - rank-bm25==0.2.2
    - scikit-learn==1.6.1
    - sentence-transformers==4.1.0
    - timm==1.0.15
    - tqdm==4.67.1
    - transformers==4.51.3
    - wandb==0.19.9